const fs = require('fs');
const path = require('path');

const locales = ['en', 'hi', 'bn', 'te', 'ta', 'mr', 'gu', 'kn', 'pa'];

const english = {
  "nav": {
    "home": "Home",
    "howItWorks": "How It Works",
    "timeline": "Timeline",
    "assistant": "Ask VoteIQ",
    "about": "About",
    "checkVoterId": "Check Voter ID",
    "guide": "Guide",
    "forms": "Forms",
    "trySimulation": "🗳️ Try Simulation",
    "aiChat": "AI Chat"
  },
  "hero": {
    "headline": "Every Vote Shapes a Nation.",
    "subheadline": "Understand the complete Indian election process — from voter registration to result declaration.",
    "ctaPrimary": "Explore the Process",
    "ctaSecondary": "Ask a Question",
    "practiceVoting": "🗳️ Practice Voting"
  },
  "flow": {
    "back": "Back",
    "startOver": "Start Over",
    "stepOf": "Step {current} of {total}",
    "stepByStep": "Step-by-Step Chatbot",
    "guideTitle": "Your Personalised Voter Guide",
    "guideSubtitle": "Answer a few questions and get tailored instructions — no searching through PDFs required."
  },
  "chat": {
    "placeholder": "Ask anything about Indian elections...",
    "send": "Send",
    "thinking": "VoteIQ is thinking...",
    "suggestedQuestions": {
      "register": "How do I register to vote?",
      "counting": "What happens on counting day?",
      "mcc": "What is the Model Code of Conduct?",
      "evm": "How does an EVM work?"
    },
    "errorMessage": "Something went wrong. Please try again."
  },
  "timeline": {
    "title": "Election Timeline",
    "subtitle": "Key milestones in a General Election cycle"
  },
  "simulation": {
    "title": "Voting Simulation",
    "instruction": "Select your candidate and press the blue button",
    "confirm": "Cast Vote",
    "successTitle": "Vote Recorded!",
    "successMessage": "Your vote has been successfully cast."
  },
  "boothLocator": {
    "title": "Find Your Polling Booth",
    "searchPlaceholder": "Enter your name or EPIC number",
    "search": "Search",
    "noResults": "No booth found. Please check your details.",
    "loading": "Searching...",
    "caption": "Polling Booth"
  },
  "shareCard": {
    "title": "Share Your Voter Pride",
    "download": "Download Card",
    "successToast": "Card downloaded successfully!",
    "caption": "Spread the Word",
    "subtitle": "Download a personalised voter card and inspire others to register and vote."
  },
  "footer": {
    "disclaimer": "Not affiliated with ECI. Educational use only.",
    "officialResources": "Official Resources",
    "quickLinks": "Quick Links",
    "builtForDemocracy": "Built for democracy · Data sourced from",
    "notOfficial": "Not an official government service",
    "voterHelpline": "Voter Helpline:"
  },
  "common": {
    "loading": "Loading...",
    "error": "Something went wrong.",
    "retry": "Try Again",
    "learnMore": "Learn More",
    "close": "Close"
  }
};

const translations = {
  hi: { nav: { home: "होम", howItWorks: "यह कैसे काम करता है", timeline: "समयरेखा", assistant: "VoteIQ से पूछें", about: "हमारे बारे में", checkVoterId: "वोटर आईडी जांचें", guide: "मार्गदर्शिका", forms: "फ़ॉर्म", trySimulation: "🗳️ सिमुलेशन आज़माएं", aiChat: "एआई चैट" }, hero: { headline: "हर वोट एक राष्ट्र को आकार देता है।", subheadline: "मतदाता पंजीकरण से लेकर परिणाम घोषणा तक - संपूर्ण भारतीय चुनाव प्रक्रिया को समझें।", ctaPrimary: "प्रक्रिया का अन्वेषण करें", ctaSecondary: "एक प्रश्न पूछें", practiceVoting: "🗳️ मतदान का अभ्यास करें" }, flow: { back: "वापस", startOver: "फिर से शुरू करें", stepOf: "चरण {current} में से {total}", stepByStep: "चरण-दर-चरण चैटबॉट", guideTitle: "आपकी व्यक्तिगत मतदाता मार्गदर्शिका", guideSubtitle: "कुछ सवालों के जवाब दें और अनुकूलित निर्देश प्राप्त करें - पीडीएफ में खोजने की कोई आवश्यकता नहीं है।" }, chat: { placeholder: "भारतीय चुनावों के बारे में कुछ भी पूछें...", send: "भेजें", thinking: "VoteIQ सोच रहा है...", suggestedQuestions: { register: "मैं वोट देने के लिए पंजीकरण कैसे करूँ?", counting: "गिनती के दिन क्या होता है?", mcc: "आदर्श आचार संहिता क्या है?", evm: "EVM कैसे काम करता है?" }, errorMessage: "कुछ गलत हो गया। कृपया पुन: प्रयास करें।" }, timeline: { title: "चुनाव समयरेखा", subtitle: "आम चुनाव चक्र में प्रमुख मील के पत्थर" }, simulation: { title: "मतदान सिमुलेशन", instruction: "अपने उम्मीदवार का चयन करें और नीला बटन दबाएं", confirm: "वोट डालें", successTitle: "वोट दर्ज किया गया!", successMessage: "आपका वोट सफलतापूर्वक डाला गया है।" }, boothLocator: { title: "अपना मतदान केंद्र खोजें", searchPlaceholder: "अपना नाम या ईपीआईसी नंबर दर्ज करें", search: "खोजें", noResults: "कोई बूथ नहीं मिला। कृपया अपना विवरण जांचें।", loading: "खोज रहा है...", caption: "मतदान केंद्र" }, shareCard: { title: "अपना मतदाता गौरव साझा करें", download: "कार्ड डाउनलोड करें", successToast: "कार्ड सफलतापूर्वक डाउनलोड हो गया!", caption: "बात फैलाएं", subtitle: "एक वैयक्तिकृत मतदाता कार्ड डाउनलोड करें और दूसरों को पंजीकरण और मतदान के लिए प्रेरित करें।" }, footer: { disclaimer: "ECI से संबद्ध नहीं। केवल शैक्षिक उपयोग के लिए।", officialResources: "आधिकारिक संसाधन", quickLinks: "त्वरित लिंक", builtForDemocracy: "लोकतंत्र के लिए निर्मित · डेटा", notOfficial: "कोई आधिकारिक सरकारी सेवा नहीं", voterHelpline: "मतदाता हेल्पलाइन:" }, common: { loading: "लोड हो रहा है...", error: "कुछ गलत हो गया।", retry: "पुन: प्रयास करें", learnMore: "और जानें", close: "बंद करें" } },
  bn: { nav: { home: "হোম", howItWorks: "কীভাবে কাজ করে", timeline: "সময়রেখা", assistant: "VoteIQ কে জিজ্ঞাসা করুন", about: "আমাদের সম্পর্কে", checkVoterId: "ভোটার আইডি চেক করুন", guide: "গাইড", forms: "ফর্ম", trySimulation: "🗳️ সিমুলেশন চেষ্টা করুন", aiChat: "এআই চ্যাট" }, hero: { headline: "প্রতিটি ভোট একটি জাতি গঠন করে।", subheadline: "ভোটার নিবন্ধন থেকে ফলাফল ঘোষণা পর্যন্ত - সম্পূর্ণ ভারতীয় নির্বাচন প্রক্রিয়াটি বুঝুন।", ctaPrimary: "প্রক্রিয়াটি অন্বেষণ করুন", ctaSecondary: "একটি প্রশ্ন করুন", practiceVoting: "🗳️ ভোটদান অনুশীলন করুন" }, flow: { back: "ফিরে যান", startOver: "আবার শুরু করুন", stepOf: "ধাপ {current} এর {total}", stepByStep: "ধাপে ধাপে চ্যাটবট", guideTitle: "আপনার ব্যক্তিগতকৃত ভোটার গাইড", guideSubtitle: "কয়েকটি প্রশ্নের উত্তর দিন এবং উপযুক্ত নির্দেশাবলী পান - পিডিএফ-এ খোঁজার প্রয়োজন নেই।" }, chat: { placeholder: "ভারতীয় নির্বাচন সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন...", send: "পাঠান", thinking: "VoteIQ ভাবছে...", suggestedQuestions: { register: "আমি কীভাবে ভোট দেওয়ার জন্য নিবন্ধন করব?", counting: "গণনার দিন কী ঘটে?", mcc: "আদর্শ আচরণবিধি কী?", evm: "ইভিএম কীভাবে কাজ করে?" }, errorMessage: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।" }, timeline: { title: "নির্বাচন সময়রেখা", subtitle: "সাধারণ নির্বাচন চক্রের মূল মাইলফলক" }, simulation: { title: "ভোটদান সিমুলেশন", instruction: "আপনার প্রার্থী নির্বাচন করুন এবং নীল বোতাম টিপুন", confirm: "ভোট দিন", successTitle: "ভোট রেকর্ড করা হয়েছে!", successMessage: "আপনার ভোট সফলভাবে দেওয়া হয়েছে।" }, boothLocator: { title: "আপনার ভোটকেন্দ্র খুঁজুন", searchPlaceholder: "আপনার নাম বা এপিক নম্বর লিখুন", search: "অনুসন্ধান করুন", noResults: "কোনো বুথ পাওয়া যায়নি। আপনার বিবরণ পরীক্ষা করুন।", loading: "অনুসন্ধান করা হচ্ছে...", caption: "ভোটকেন্দ্র" }, shareCard: { title: "আপনার ভোটার গর্ব ভাগ করুন", download: "কার্ড ডাউনলোড করুন", successToast: "কার্ড সফলভাবে ডাউনলোড হয়েছে!", caption: "কথাটি ছড়িয়ে দিন", subtitle: "একটি ব্যক্তিগতকৃত ভোটার কার্ড ডাউনলোড করুন এবং অন্যদের নিবন্ধন ও ভোট দিতে অনুপ্রাণিত করুন।" }, footer: { disclaimer: "ECI এর সাথে যুক্ত নয়। শুধুমাত্র শিক্ষামূলক ব্যবহারের জন্য।", officialResources: "অফিসিয়াল সম্পদ", quickLinks: "দ্রুত লিঙ্ক", builtForDemocracy: "গণতন্ত্রের জন্য নির্মিত · ডেটা", notOfficial: "কোনো অফিসিয়াল সরকারি পরিষেবা নয়", voterHelpline: "ভোটার হেল্পলাইন:" }, common: { loading: "লোড হচ্ছে...", error: "কিছু ভুল হয়েছে।", retry: "আবার চেষ্টা করুন", learnMore: "আরও জানুন", close: "বন্ধ করুন" } },
  te: { nav: { home: "హోమ్", howItWorks: "ఇది ఎలా పనిచేస్తుంది", timeline: "కాలక్రమం", assistant: "VoteIQ ని అడగండి", about: "మా గురించి", checkVoterId: "ఓటరు IDని తనిఖీ చేయండి", guide: "మార్గదర్శి", forms: "ఫారమ్‌లు", trySimulation: "🗳️ అనుకరణను ప్రయత్నించండి", aiChat: "AI చాట్" }, hero: { headline: "ప్రతి ఓటు ఒక దేశాన్ని నిర్మిస్తుంది.", subheadline: "ఓటరు నమోదు నుండి ఫలితాల ప్రకటన వరకు - మొత్తం భారతీయ ఎన్నికల ప్రక్రియను అర్థం చేసుకోండి.", ctaPrimary: "ప్రక్రియను అన్వేషించండి", ctaSecondary: "ఒక ప్రశ్న అడగండి", practiceVoting: "🗳️ ఓటింగ్ ప్రాక్టీస్ చేయండి" }, flow: { back: "వెనుకకు", startOver: "మళ్లీ ప్రారంభించండి", stepOf: "దశ {current} లో {total}", stepByStep: "దశల వారీ చాట్‌బాట్", guideTitle: "మీ వ్యక్తిగతీకరించిన ఓటరు మార్గదర్శి", guideSubtitle: "కొన్ని ప్రశ్నలకు సమాధానం ఇవ్వండి మరియు అనుకూల సూచనలను పొందండి - PDF లలో శోధించాల్సిన అవసరం లేదు." }, chat: { placeholder: "భారతీయ ఎన్నికల గురించి ఏదైనా అడగండి...", send: "పంపండి", thinking: "VoteIQ ఆలోచిస్తోంది...", suggestedQuestions: { register: "నేను ఓటు వేయడానికి ఎలా నమోదు చేసుకోవాలి?", counting: "కౌంటింగ్ రోజున ఏమి జరుగుతుంది?", mcc: "మోడల్ కోడ్ ఆఫ్ కండక్ట్ అంటే ఏమిటి?", evm: "EVM ఎలా పనిచేస్తుంది?" }, errorMessage: "ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి." }, timeline: { title: "ఎన్నికల కాలక్రమం", subtitle: "సార్వత్రిక ఎన్నికల చక్రంలో ముఖ్యమైన మైలురాళ్ళు" }, simulation: { title: "ఓటింగ్ అనుకరణ", instruction: "మీ అభ్యర్థిని ఎంచుకుని బ్లూ బటన్ నొక్కండి", confirm: "ఓటు వేయండి", successTitle: "ఓటు నమోదైంది!", successMessage: "మీ ఓటు విజయవంతంగా వేయబడింది." }, boothLocator: { title: "మీ పోలింగ్ బూత్‌ను కనుగొనండి", searchPlaceholder: "మీ పేరు లేదా EPIC నంబర్‌ను నమోదు చేయండి", search: "శోధించండి", noResults: "బూత్ కనుగొనబడలేదు. దయచేసి మీ వివరాలను తనిఖీ చేయండి.", loading: "శోధిస్తోంది...", caption: "పోలింగ్ బూత్" }, shareCard: { title: "మీ ఓటరు గర్వాన్ని పంచుకోండి", download: "కార్డ్‌ని డౌన్‌లోడ్ చేయండి", successToast: "కార్డ్ విజయవంతంగా డౌన్‌లోడ్ చేయబడింది!", caption: "ప్రచారం చేయండి", subtitle: "వ్యక్తిగతీకరించిన ఓటరు కార్డ్‌ని డౌన్‌లోడ్ చేయండి మరియు నమోదు చేసుకోవడానికి మరియు ఓటు వేయడానికి ఇతరులను ప్రేరేపించండి." }, footer: { disclaimer: "ECI తో అనుబంధించబడలేదు. విద్యా ప్రయోజనాల కోసం మాత్రమే.", officialResources: "అధికారిక వనరులు", quickLinks: "త్వరిత లింకులు", builtForDemocracy: "ప్రజాస్వామ్యం కోసం నిర్మించబడింది · డేటా", notOfficial: "అధికారిక ప్రభుత్వ సేవ కాదు", voterHelpline: "ఓటరు హెల్ప్‌లైన్:" }, common: { loading: "లోడ్ అవుతోంది...", error: "ఏదో తప్పు జరిగింది.", retry: "మళ్లీ ప్రయత్నించండి", learnMore: "ఇంకా తెలుసుకోండి", close: "మూసివేయి" } },
  ta: { nav: { home: "முகப்பு", howItWorks: "எப்படிச் செயல்படுகிறது", timeline: "காலக்கோடு", assistant: "VoteIQ-ஐக் கேளுங்கள்", about: "எங்களை பற்றி", checkVoterId: "வாக்காளர் ஐடியை சரிபார்க்கவும்", guide: "வழிகாட்டி", forms: "படிவங்கள்", trySimulation: "🗳️ உருவகப்படுத்துதலை முயற்சிக்கவும்", aiChat: "AI அரட்டை" }, hero: { headline: "ஒவ்வொரு வாக்கும் ஒரு தேசத்தை உருவாக்குகிறது.", subheadline: "வாக்காளர் பதிவு முதல் முடிவு அறிவிப்பு வரை - முழு இந்திய தேர்தல் செயல்முறையையும் புரிந்து கொள்ளுங்கள்.", ctaPrimary: "செயல்முறையை ஆராயுங்கள்", ctaSecondary: "ஒரு கேள்வியைக் கேளுங்கள்", practiceVoting: "🗳️ வாக்குப்பதிவு பயிற்சி" }, flow: { back: "பின்னே", startOver: "மீண்டும் தொடங்கு", stepOf: "படி {current} இல் {total}", stepByStep: "படிப்படியான சாட்போட்", guideTitle: "உங்கள் தனிப்பயனாக்கப்பட்ட வாக்காளர் வழிகாட்டி", guideSubtitle: "சில கேள்விகளுக்கு பதிலளித்து பொருத்தமான வழிமுறைகளைப் பெறுங்கள் - PDF களில் தேட வேண்டியதில்லை." }, chat: { placeholder: "இந்திய தேர்தல்கள் பற்றி எதையும் கேளுங்கள்...", send: "அனுப்பு", thinking: "VoteIQ யோசிக்கிறது...", suggestedQuestions: { register: "வாக்களிக்க நான் எவ்வாறு பதிவு செய்வது?", counting: "எண்ணும் நாளில் என்ன நடக்கும்?", mcc: "மாதிரி நடத்தை விதி என்றால் என்ன?", evm: "EVM எவ்வாறு செயல்படுகிறது?" }, errorMessage: "ஏதோ தவறு நடந்துவிட்டது. மீண்டும் முயற்சிக்கவும்." }, timeline: { title: "தேர்தல் காலக்கோடு", subtitle: "பொதுத் தேர்தல் சுழற்சியில் முக்கிய மைல்கற்கள்" }, simulation: { title: "வாக்குப்பதிவு உருவகப்படுத்துதல்", instruction: "உங்கள் வேட்பாளரைத் தேர்ந்தெடுத்து நீல பொத்தானை அழுத்தவும்", confirm: "வாக்களிக்கவும்", successTitle: "வாக்கு பதிவு செய்யப்பட்டது!", successMessage: "உங்கள் வாக்கு வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளது." }, boothLocator: { title: "உங்கள் வாக்குச் சாவடியைக் கண்டறியவும்", searchPlaceholder: "உங்கள் பெயர் அல்லது EPIC எண்ணை உள்ளிடவும்", search: "தேடு", noResults: "சாவடி எதுவும் கிடைக்கவில்லை. உங்கள் விவரங்களை சரிபார்க்கவும்.", loading: "தேடுகிறது...", caption: "வாக்குச்சாவடி" }, shareCard: { title: "உங்கள் வாக்காளர் பெருமையைப் பகிரவும்", download: "அட்டையைப் பதிவிறக்கவும்", successToast: "அட்டை வெற்றிகரமாக பதிவிறக்கப்பட்டது!", caption: "பரப்புங்கள்", subtitle: "தனிப்பயனாக்கப்பட்ட வாக்காளர் அட்டையைப் பதிவிறக்கம் செய்து பதிவு செய்யவும் வாக்களிக்கவும் மற்றவர்களை ஊக்குவிக்கவும்." }, footer: { disclaimer: "ECI உடன் இணைக்கப்படவில்லை. கல்வி பயன்பாட்டிற்கு மட்டுமே.", officialResources: "அதிகாரப்பூர்வ வளங்கள்", quickLinks: "விரைவான இணைப்புகள்", builtForDemocracy: "ஜனநாயகத்திற்காக உருவாக்கப்பட்டது · தரவு", notOfficial: "அதிகாரப்பூர்வ அரசு சேவை இல்லை", voterHelpline: "வாக்காளர் ஹெல்ப்லைன்:" }, common: { loading: "ஏற்றுகிறது...", error: "ஏதோ தவறு நடந்துவிட்டது.", retry: "மீண்டும் முயற்சிக்கவும்", learnMore: "மேலும் அறிய", close: "மூடு" } },
  mr: { nav: { home: "मुख्यपृष्ठ", howItWorks: "हे कसे कार्य करते", timeline: "वेळापत्रक", assistant: "VoteIQ ला विचारा", about: "आमच्याबद्दल", checkVoterId: "मतदार ओळखपत्र तपासा", guide: "मार्गदर्शक", forms: "फॉर्म", trySimulation: "🗳️ सिम्युलेशन वापरून पहा", aiChat: "AI चॅट" }, hero: { headline: "प्रत्येक मत एका राष्ट्राला आकार देते.", subheadline: "मतदार नोंदणीपासून ते निकाल घोषणेपर्यंत - संपूर्ण भारतीय निवडणूक प्रक्रिया समजून घ्या.", ctaPrimary: "प्रक्रिया एक्सप्लोर करा", ctaSecondary: "एक प्रश्न विचारा", practiceVoting: "🗳️ मतदानाचा सराव करा" }, flow: { back: "मागे", startOver: "पुन्हा सुरू करा", stepOf: "पायरी {current} पैकी {total}", stepByStep: "टप्प्याटप्प्याने चॅटबॉट", guideTitle: "तुमचे वैयक्तिकृत मतदार मार्गदर्शक", guideSubtitle: "काही प्रश्नांची उत्तरे द्या आणि सानुकूलित सूचना मिळवा - PDF मध्ये शोधण्याची गरज नाही." }, chat: { placeholder: "भारतीय निवडणुकांबाबत काहीही विचारा...", send: "पाठवा", thinking: "VoteIQ विचार करत आहे...", suggestedQuestions: { register: "मतदानासाठी मी नोंदणी कशी करू?", counting: "मोजणीच्या दिवशी काय होते?", mcc: "आदर्श आचारसंहिता काय आहे?", evm: "ईव्हीएम कसे काम करते?" }, errorMessage: "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा." }, timeline: { title: "निवडणूक वेळापत्रक", subtitle: "सार्वत्रिक निवडणूक चक्रातील प्रमुख टप्पे" }, simulation: { title: "मतदान सिम्युलेशन", instruction: "तुमचा उमेदवार निवडा आणि निळे बटण दाबा", confirm: "मत द्या", successTitle: "मत नोंदवले गेले!", successMessage: "तुमचे मत यशस्वीरित्या दिले गेले आहे." }, boothLocator: { title: "तुमचे मतदान केंद्र शोधा", searchPlaceholder: "तुमचे नाव किंवा EPIC क्रमांक प्रविष्ट करा", search: "शोधा", noResults: "कोणतेही बूथ आढळले नाही. कृपया तुमचे तपशील तपासा.", loading: "शोधत आहे...", caption: "मतदान केंद्र" }, shareCard: { title: "तुमचा मतदार अभिमान शेअर करा", download: "कार्ड डाउनलोड करा", successToast: "कार्ड यशस्वीरित्या डाउनलोड केले!", caption: "माहिती पसरवा", subtitle: "वैयक्तिकृत मतदार कार्ड डाउनलोड करा आणि इतरांना नोंदणी आणि मतदान करण्यास प्रेरित करा." }, footer: { disclaimer: "ECI शी संलग्न नाही. फक्त शैक्षणिक वापरासाठी.", officialResources: "अधिकृत संसाधने", quickLinks: "जलद दुवे", builtForDemocracy: "लोकशाहीसाठी बनवले · डेटा", notOfficial: "कोणतीही अधिकृत सरकारी सेवा नाही", voterHelpline: "मतदार हेल्पलाइन:" }, common: { loading: "लोड होत आहे...", error: "काहीतरी चूक झाली.", retry: "पुन्हा प्रयत्न करा", learnMore: "अधिक जाणून घ्या", close: "बंद करा" } },
  gu: { nav: { home: "હોમ", howItWorks: "તે કેવી રીતે કાર્ય કરે છે", timeline: "સમયરેખા", assistant: "VoteIQ ને પૂછો", about: "અમારા વિશે", checkVoterId: "મતદાર ID ચકાસો", guide: "માર્ગદર્શિકા", forms: "ફોર્મ", trySimulation: "🗳️ સિમ્યુલેશનનો પ્રયાસ કરો", aiChat: "AI ચેટ" }, hero: { headline: "દરેક મત એક રાષ્ટ્રનું નિર્માણ કરે છે.", subheadline: "મતદાર નોંધણીથી લઈને પરિણામની જાહેરાત સુધી - સંપૂર્ણ ભારતીય ચૂંટણી પ્રક્રિયાને સમજો.", ctaPrimary: "પ્રક્રિયાનું અન્વેષણ કરો", ctaSecondary: "એક પ્રશ્ન પૂછો", practiceVoting: "🗳️ મતદાનની પ્રેક્ટિસ કરો" }, flow: { back: "પાછા", startOver: "ફરીથી શરૂ કરો", stepOf: "પગલું {current} નું {total}", stepByStep: "સ્ટેપ-બાય-સ્ટેપ ચેટબોટ", guideTitle: "તમારી વ્યક્તિગત મતદાર માર્ગદર્શિકા", guideSubtitle: "થોડા પ્રશ્નોના જવાબો આપો અને કસ્ટમાઇઝ્ડ સૂચનાઓ મેળવો - પીડીએફમાં શોધવાની કોઈ જરૂર નથી." }, chat: { placeholder: "ભારતીય ચૂંટણીઓ વિશે કંઈપણ પૂછો...", send: "મોકલો", thinking: "VoteIQ વિચારી રહ્યું છે...", suggestedQuestions: { register: "હું મતદાન કરવા માટે કેવી રીતે નોંધણી કરું?", counting: "ગણતરીના દિવસે શું થાય છે?", mcc: "આદર્શ આચાર સંહિતા શું છે?", evm: "EVM કેવી રીતે કામ કરે છે?" }, errorMessage: "કંઈક ખોટું થયું. કૃપા કરીને ફરી પ્રયાસ કરો." }, timeline: { title: "ચૂંટણી સમયરેખા", subtitle: "સામાન્ય ચૂંટણી ચક્રમાં મુખ્ય લક્ષ્યો" }, simulation: { title: "મતદાન સિમ્યુલેશન", instruction: "તમારો ઉમેદવાર પસંદ કરો અને વાદળી બટન દબાવો", confirm: "મત આપો", successTitle: "મત નોંધાયેલ છે!", successMessage: "તમારો મત સફળતાપૂર્વક અપાઈ ગયો છે." }, boothLocator: { title: "તમારું મતદાન મથક શોધો", searchPlaceholder: "તમારું નામ અથવા EPIC નંબર દાખલ કરો", search: "શોધો", noResults: "કોઈ બૂથ મળ્યું નથી. કૃપા કરીને તમારી વિગતો તપાસો.", loading: "શોધી રહ્યું છે...", caption: "મતદાન મથક" }, shareCard: { title: "તમારું મતદાર ગૌરવ શેર કરો", download: "કાર્ડ ડાઉનલોડ કરો", successToast: "કાર્ડ સફળતાપૂર્વક ડાઉનલોડ થયું!", caption: "વાત ફેલાવો", subtitle: "વ્યક્તિગત મતદાર કાર્ડ ડાઉનલોડ કરો અને અન્ય લોકોને નોંધણી અને મતદાન કરવા માટે પ્રેરણા આપો." }, footer: { disclaimer: "ECI સાથે જોડાયેલ નથી. માત્ર શૈક્ષણિક ઉપયોગ માટે.", officialResources: "સત્તાવાર સંસાધનો", quickLinks: "ઝડપી લિંક્સ", builtForDemocracy: "લોકશાહી માટે બનાવેલ · ડેટા", notOfficial: "કોઈ સત્તાવાર સરકારી સેવા નથી", voterHelpline: "મતદાર હેલ્પલાઇન:" }, common: { loading: "લોડ થઈ રહ્યું છે...", error: "કંઈક ખોટું થયું.", retry: "ફરી પ્રયાસ કરો", learnMore: "વધુ જાણો", close: "બંધ કરો" } },
  kn: { nav: { home: "ಮುಖಪುಟ", howItWorks: "ಇದು ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ", timeline: "ಟೈಮ್‌ಲೈನ್", assistant: "VoteIQ ಅನ್ನು ಕೇಳಿ", about: "ನಮ್ಮ ಬಗ್ಗೆ", checkVoterId: "ಮತದಾರರ ಐಡಿಯನ್ನು ಪರಿಶೀಲಿಸಿ", guide: "ಮಾರ್ಗದರ್ಶಿ", forms: "ಫಾರ್ಮ್‌ಗಳು", trySimulation: "🗳️ ಸಿಮ್ಯುಲೇಶನ್ ಪ್ರಯತ್ನಿಸಿ", aiChat: "AI ಚಾಟ್" }, hero: { headline: "ಪ್ರತಿಯೊಂದು ಮತವು ರಾಷ್ಟ್ರವನ್ನು ರೂಪಿಸುತ್ತದೆ.", subheadline: "ಮತದಾರರ ನೋಂದಣಿಯಿಂದ ಫಲಿತಾಂಶ ಘೋಷಣೆಯವರೆಗೆ - ಸಂಪೂರ್ಣ ಭಾರತೀಯ ಚುನಾವಣಾ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.", ctaPrimary: "ಪ್ರಕ್ರಿಯೆಯನ್ನು ಅನ್ವೇಷಿಸಿ", ctaSecondary: "ಒಂದು ಪ್ರಶ್ನೆ ಕೇಳಿ", practiceVoting: "🗳️ ಮತದಾನವನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ" }, flow: { back: "ಹಿಂದೆ", startOver: "ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ", stepOf: "ಹಂತ {current} ರಲ್ಲಿ {total}", stepByStep: "ಹಂತ-ಹಂತದ ಚಾಟ್‌ಬಾಟ್", guideTitle: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಮತದಾರರ ಮಾರ್ಗದರ್ಶಿ", guideSubtitle: "ಕೆಲವು ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ ಮತ್ತು ಕಸ್ಟಮೈಸ್ ಮಾಡಿದ ಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ - ಪಿಡಿಎಫ್‌ಗಳಲ್ಲಿ ಹುಡುಕುವ ಅಗತ್ಯವಿಲ್ಲ." }, chat: { placeholder: "ಭಾರತೀಯ ಚುನಾವಣೆಗಳ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ...", send: "ಕಳುಹಿಸಿ", thinking: "VoteIQ ಯೋಚಿಸುತ್ತಿದೆ...", suggestedQuestions: { register: "ಮತದಾನ ಮಾಡಲು ನಾನು ಹೇಗೆ ನೋಂದಾಯಿಸಿಕೊಳ್ಳುವುದು?", counting: "ಎಣಿಕೆ ದಿನದಂದು ಏನಾಗುತ್ತದೆ?", mcc: "ಮಾದರಿ ನೀತಿ ಸಂಹಿತೆ ಎಂದರೇನು?", evm: "ಇವಿಎಂ ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ?" }, errorMessage: "ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ." }, timeline: { title: "ಚುನಾವಣಾ ಟೈಮ್‌ಲೈನ್", subtitle: "ಸಾರ್ವತ್ರಿಕ ಚುನಾವಣಾ ಚಕ್ರದಲ್ಲಿ ಪ್ರಮುಖ ಮೈಲಿಗಲ್ಲುಗಳು" }, simulation: { title: "ಮತದಾನ ಸಿಮ್ಯುಲೇಶನ್", instruction: "ನಿಮ್ಮ ಅಭ್ಯರ್ಥಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ನೀಲಿ ಗುಂಡಿಯನ್ನು ಒತ್ತಿ", confirm: "ಮತ ಚಲಾಯಿಸಿ", successTitle: "ಮತ ದಾಖಲಾಗಿದೆ!", successMessage: "ನಿಮ್ಮ ಮತವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಚಲಾಯಿಸಲಾಗಿದೆ." }, boothLocator: { title: "ನಿಮ್ಮ ಮತಗಟ್ಟೆಯನ್ನು ಹುಡುಕಿ", searchPlaceholder: "ನಿಮ್ಮ ಹೆಸರು ಅಥವಾ ಎಪಿಕ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ", search: "ಹುಡುಕಿ", noResults: "ಯಾವುದೇ ಬೂತ್ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.", loading: "ಹುಡುಕಲಾಗುತ್ತಿದೆ...", caption: "ಮತಗಟ್ಟೆ" }, shareCard: { title: "ನಿಮ್ಮ ಮತದಾರರ ಹೆಮ್ಮೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ", download: "ಕಾರ್ಡ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ", successToast: "ಕಾರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಡೌನ್‌ಲೋಡ್ ಆಗಿದೆ!", caption: "ಹರಡಿ", subtitle: "ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಮತದಾರರ ಕಾರ್ಡ್ ಅನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ನೋಂದಾಯಿಸಲು ಮತ್ತು ಮತ ಚಲಾಯಿಸಲು ಇತರರನ್ನು ಪ್ರೇರೇಪಿಸಿ." }, footer: { disclaimer: "ECI ಯೊಂದಿಗೆ ಸಂಯೋಜಿತವಾಗಿಲ್ಲ. ಶೈಕ್ಷಣಿಕ ಬಳಕೆಗೆ ಮಾತ್ರ.", officialResources: "ಅಧಿಕೃತ ಸಂಪನ್ಮೂಲಗಳು", quickLinks: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು", builtForDemocracy: "ಪ್ರಜಾಪ್ರಭುತ್ವಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ · ಡೇಟಾ", notOfficial: "ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಸೇವೆ ಅಲ್ಲ", voterHelpline: "ಮತದಾರರ ಸಹಾಯವಾಣಿ:" }, common: { loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...", error: "ಏನೋ ತಪ್ಪಾಗಿದೆ.", retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ", learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ", close: "ಮುಚ್ಚಿ" } },
  pa: { nav: { home: "ਮੁੱਖ ਪੰਨਾ", howItWorks: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ", timeline: "ਟਾਈਮਲਾਈਨ", assistant: "VoteIQ ਨੂੰ ਪੁੱਛੋ", about: "ਸਾਡੇ ਬਾਰੇ", checkVoterId: "ਵੋਟਰ ਆਈਡੀ ਦੀ ਜਾਂਚ ਕਰੋ", guide: "ਗਾਈਡ", forms: "ਫਾਰਮ", trySimulation: "🗳️ ਸਿਮੂਲੇਸ਼ਨ ਅਜ਼ਮਾਓ", aiChat: "AI ਚੈਟ" }, hero: { headline: "ਹਰ ਵੋਟ ਇੱਕ ਰਾਸ਼ਟਰ ਬਣਾਉਂਦਾ ਹੈ।", subheadline: "ਵੋਟਰ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਤੋਂ ਲੈ ਕੇ ਨਤੀਜੇ ਦੇ ਐਲਾਨ ਤੱਕ - ਪੂਰੀ ਭਾਰਤੀ ਚੋਣ ਪ੍ਰਕਿਰਿਆ ਨੂੰ ਸਮਝੋ।", ctaPrimary: "ਪ੍ਰਕਿਰਿਆ ਦੀ ਪੜਚੋਲ ਕਰੋ", ctaSecondary: "ਇੱਕ ਸਵਾਲ ਪੁੱਛੋ", practiceVoting: "🗳️ ਵੋਟਿੰਗ ਦਾ ਅਭਿਆਸ ਕਰੋ" }, flow: { back: "ਪਿੱਛੇ", startOver: "ਦੁਬਾਰਾ ਸ਼ੁਰੂ ਕਰੋ", stepOf: "ਕਦਮ {current} ਵਿੱਚੋਂ {total}", stepByStep: "ਕਦਮ-ਦਰ-ਕਦਮ ਚੈਟਬੋਟ", guideTitle: "ਤੁਹਾਡੀ ਵਿਅਕਤੀਗਤ ਵੋਟਰ ਗਾਈਡ", guideSubtitle: "ਕੁਝ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ ਅਤੇ ਅਨੁਕੂਲਿਤ ਹਿਦਾਇਤਾਂ ਪ੍ਰਾਪਤ ਕਰੋ - PDF ਵਿੱਚ ਖੋਜਣ ਦੀ ਕੋਈ ਲੋੜ ਨਹੀਂ।" }, chat: { placeholder: "ਭಾರਤੀ ਚੋਣਾਂ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ...", send: "ਭੇਜੋ", thinking: "VoteIQ ਸੋਚ ਰਿਹਾ ਹੈ...", suggestedQuestions: { register: "ਮੈਂ ਵੋਟ ਪਾਉਣ ਲਈ ਕਿਵੇਂ ਰਜਿਸਟਰ ਕਰਾਂ?", counting: "ਗਿਣਤੀ ਵਾਲੇ ਦਿਨ ਕੀ ਹੁੰਦਾ ਹੈ?", mcc: "ਆਦਰਸ਼ ਚੋਣ ਜ਼ਾਬਤਾ ਕੀ ਹੈ?", evm: "EVM ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ?" }, errorMessage: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।" }, timeline: { title: "ਚੋਣ ਟਾਈਮਲਾਈਨ", subtitle: "ਆਮ ਚੋਣ ਚੱਕਰ ਵਿੱਚ ਪ੍ਰਮੁੱਖ ਮੀਲ ਪੱਥਰ" }, simulation: { title: "ਵੋਟਿੰਗ ਸਿਮੂਲੇਸ਼ਨ", instruction: "ਆਪਣੇ ਉਮੀਦਵਾਰ ਦੀ ਚੋਣ ਕਰੋ ਅਤੇ ਨੀਲਾ ਬਟਨ ਦਬਾਓ", confirm: "ਵੋਟ ਪਾਓ", successTitle: "ਵੋਟ ਦਰਜ ਕੀਤੀ ਗਈ!", successMessage: "ਤੁਹਾਡੀ ਵੋਟ ਸਫਲਤਾਪੂਰਵਕ ਪਾ ਦਿੱਤੀ ਗਈ ਹੈ।" }, boothLocator: { title: "ਆਪਣਾ ਪੋਲਿੰਗ ਬੂਥ ਲੱਭੋ", searchPlaceholder: "ਆਪਣਾ ਨਾਮ ਜਾਂ ਈਪੀਆਈਸੀ ਨੰਬਰ ਦਾਖਲ ਕਰੋ", search: "ਖੋਜੋ", noResults: "ਕੋਈ ਬੂਥ ਨਹੀਂ ਮਿਲਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਵੇਰਵਿਆਂ ਦੀ ਜਾਂਚ ਕਰੋ।", loading: "ਖੋਜ ਰਿਹਾ ਹੈ...", caption: "ਪੋਲਿੰਗ ਬੂਥ" }, shareCard: { title: "ਆਪਣਾ ਵੋਟਰ ਮਾਣ ਸਾਂਝਾ ਕਰੋ", download: "ਕਾਰਡ ਡਾਊਨਲੋਡ ਕਰੋ", successToast: "ਕਾਰਡ ਸਫਲਤਾਪੂਰਵਕ ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ!", caption: "ਗੱਲ ਫੈਲਾਓ", subtitle: "ਇੱਕ ਵਿਅਕਤੀਗਤ ਵੋਟਰ ਕਾਰਡ ਡਾਊਨਲੋਡ ਕਰੋ ਅਤੇ ਹੋਰਾਂ ਨੂੰ ਰਜਿਸਟਰ ਕਰਨ ਅਤੇ ਵੋਟ ਪਾਉਣ ਲਈ ਪ੍ਰੇਰਿਤ ਕਰੋ।" }, footer: { disclaimer: "ECI ਨਾਲ ਸੰਬੰਧਿਤ ਨਹੀਂ। ਸਿਰਫ਼ ਵਿਦਿਅਕ ਵਰਤੋਂ ਲਈ।", officialResources: "ਅਧਿਕਾਰਤ ਸਰੋਤ", quickLinks: "ਤੁਰੰਤ ਲਿੰਕ", builtForDemocracy: "ਲੋਕਤੰਤਰ ਲਈ ਬਣਾਇਆ ਗਿਆ · ਡੇਟਾ", notOfficial: "ਕੋਈ ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਸੇਵਾ ਨਹੀਂ", voterHelpline: "ਵੋਟਰ ਹੈਲਪਲਾਈਨ:" }, common: { loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...", error: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।", retry: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ", learnMore: "ਹੋਰ ਜਾਣੋ", close: "ਬੰਦ ਕਰੋ" } }
};

fs.mkdirSync(path.join(__dirname, 'messages'), { recursive: true });

fs.writeFileSync(path.join(__dirname, 'messages', 'en.json'), JSON.stringify(english, null, 2));

for (const locale of locales) {
  if (locale === 'en') continue;
  fs.writeFileSync(path.join(__dirname, 'messages', `${locale}.json`), JSON.stringify(translations[locale], null, 2));
}

console.log('Done writing locales');
